### ISSUE TITLE
Engine.GetValidMoves missing valid moves

### ISSUE THREAD

**Issue by ljvankuiken** [3583Bytes/ChessCore#1]
First off, thank you for releasing the code.  Very educational and useful.
Code should demonstrate the problem. which is caused by attack boards not being regenerated after every ply.  Maybe this is your design intention.  Not sure.

Consider the following method:
`        

        static void TestValidMoves()
        {
            string startFen = "8/8/8/2k5/2P5/2N5/2N3Q1/3K4 w - - 0 1";
            ChessEngine.Engine.Engine e = new ChessEngine.Engine.Engine();
            e.InitiateBoard(startFen);

            // 1. Qg7
            e.MovePiece(54, 14);

            // returns "8/6Q1/8/2k5/2P5/2N5/2N5/3K4 w - - 2 2"
            // (I've modified 50 move logic to increment after every ply, so this may look different to you
            // but should not interfere with GetValidMoves)

            var fen1 = e.FEN;
            
            // c6
            byte square = 26;
            var pieceType = e.GetPieceTypeAt(square);
            var pieceColor = e.GetPieceColorAt(square);

            int c = square % 8;
            int r = square / 8;
            
            //  Returns { 1, 2 } { 3, 2 } and { 2, 4 } (squares 17, 19 and 34 ) square 18 not in list, even though valid.
            var vm = e.GetValidMoves((byte)c, (byte)r);
            
            // 1...Kc6  but engine allows move
            e.MovePiece(26, 18);

            // returns "8/6Q1/2k5/8/2P5/2N5/2N5/3K4 w - - 2 2"
            var fen2 = e.FEN;

            e.InitiateBoard(fen1);
            // now square 18 is included in list
            vm = e.GetValidMoves((byte)c, (byte)r);

        }
`

**Comment by 3583Bytes** [comment]
Did you ever find a solution to this?

**Comment by 3583Bytes** [comment]
I just initiated the game with the provided fen and I was able to move the king to position 18.  Not sure what I am missing?
