### ISSUE TITLE
Fixed bug that caused engine to prematurely declare checkmate against computer

### ISSUE THREAD

**Issue by jskubick** [3583Bytes/ChessCore#3]
If you're interested, I found and fixed a bug that caused the engine to prematurely declare checkmate against the computer (it's in my fork of ChessCore, specifically near the start of Engine.AiPonderMove()).

It took me a while to track down the problem, but basically the issue is that WhiteAttackBoard[] gets regenerated BEFORE the player's move gets executed, and only moves that were viable prior to that move are considered when AiPonderMove() goes to look for escape routes for a king in check. 

Board to illustrate the problem: 

r4r2/pppb1p1k/8/3p2Q1/q4P2/2np4/6PP/5RK1/ w - 0 27

then... move the white queen from G5 to H5.

Without my fix, the engine declares checkmate against black & the game is over.

With my fix, the engine correctly moves the computer's black king to G8, and proceeds to win a few moves later.

Since the performance cost of running PieceValidMoves.GenerateValidMoves(ChessBoard) is nontrivial on Android, I added an extra bit of logic so that it ALWAYS executes whenever either king is in check, but otherwise executes every turn ONLY at the two hardest difficulty levels, on the rationale that a premature declaration of checkmate is going to be noticed & confusing even to inexperienced players, but if the computer insidiously overlooks opportunities to save OTHER pieces, it's either a minor concern relative to performance, or a welcome way to make the engine slightly easier to play against.

**Comment by 3583Bytes** [comment]
That is awesome, thank you for letting me know.  I am going to try to pull this change into my repo.

**Comment by 3583Bytes** [comment]
I think you make a pull request I should be able to see a diff and approve or else I can do it manually

**Comment by jskubick** [comment]
OK, I did the pull request. Sorry about doing it as three separate commits.

For what it's worth, I finally got around to benchmarking the time it takes to make the extra call to GenerateValidMoves. On my PC (mobile i7, quad, 2.7/3.5GHz), it adds "0ms", so I guess the only real reason to not execute it 100% of the time is to intentionally give the computer a quirky blind spot at the easier difficulty levels that's not unlike the kind of mistake (overlooking a possible save) that an inexperienced human player might make.

**Comment by 3583Bytes** [comment]
Yah 1 call to GenerateValidMoves is actually not bad at all, it gets problematic when it examines 1000s of boards per second.

I think I am going to modify your code to always call PieceValidMoves regardless of difficulty

**Comment by jskubick** [comment]
Probably not a bad idea. 

Btw, if you want to see the game I wrote using it, you can get it at http://play.google.com/apps/testing/pantherkitty.pawnslaught

(I'm planning to officially release it in another day or two, but for the moment it's an open beta)

It's designed for Android with Cardboard-type VR viewers. As of now, there should be no bugs whatsoever remaining that would compromise the gameplay (I'm still swatting animation glitches, but I have a watchdog in place that kills the animation and just forcibly brings the board into agreement with the chess engine's model if it doesn't finish an animation within 12 seconds) [I'd consider any bug that ended the game & wasn't rescued by the watchdog to be an extremely serious bug.]

**Comment by 3583Bytes** [comment]
Thanks will do :)
